users = [
  {
    name: "iboya vat",
    image: "https://randomuser.me/api/portraits/thumb/women/67.jpg",
    joined: "07/15/15",
    email: "test@douglascollege.ca",
  },
  {
    name: "aapo niskanen",
    image: "https://randomuser.me/api/portraits/thumb/men/34.jpg",
    joined: "07/15/15",
    email: "test@douglascollege.ca",
  },
  {
    name: "zilda moreira",
    image: "https://randomuser.me/api/portraits/thumb/women/38.jpg",
    joined: "07/15/15",
    email: "test@douglascollege.ca",
  },
  {
    name: "lilou le gall",
    image: "https://randomuser.me/api/portraits/thumb/women/23.jpg",
    joined: "07/15/15",
    email: "test@douglascollege.ca",
  },
  {
    name: "lucy hall",
    image: "https://randomuser.me/api/portraits/thumb/women/24.jpg",
    joined: "07/15/15",
    email: "test@douglascollege.ca",
  },
  {
    name: "sara alves",
    image: "https://randomuser.me/api/portraits/thumb/women/14.jpg",
    joined: "07/15/15",
    email: "test@douglascollege.ca",
  },
  {
    name: "ramon macrae",
    image: "https://randomuser.me/api/portraits/thumb/men/49.jpg",
    joined: "07/15/15",
    email: "test@douglascollege.ca",
  },
  {
    name: "connor taylor",
    image: "https://randomuser.me/api/portraits/thumb/men/15.jpg",
    joined: "07/15/15",
    email: "test@douglascollege.ca",
  },
  {
    name: "aymeric morel",
    image: "https://randomuser.me/api/portraits/thumb/men/11.jpg",
    joined: "07/15/15",
    email: "test@douglascollege.ca",
  },
  {
    name: "lorenz otto",
    image: "https://randomuser.me/api/portraits/thumb/men/49.jpg",
    joined: "07/15/15",
    email: "test@douglascollege.ca",
  },
  {
    name: "karl williamson",
    image: "https://randomuser.me/api/portraits/thumb/men/29.jpg",
    joined: "07/15/15",
    email: "test@douglascollege.ca",
  },
  {
    name: "ouassim heering",
    image: "https://randomuser.me/api/portraits/thumb/men/34.jpg",
    joined: "07/15/15",
    email: "test@douglascollege.ca",
  },
  {
    name: "roberto molina",
    image: "https://randomuser.me/api/portraits/thumb/men/91.jpg",
    joined: "06/03/15",
    email: "test@douglascollege.ca",
  },
  {
    name: "jordan hubert",
    image: "https://randomuser.me/api/portraits/thumb/men/28.jpg",
    joined: "06/03/15",
    email: "test@douglascollege.ca",
  },
  {
    name: "melvin baker",
    image: "https://randomuser.me/api/portraits/thumb/men/29.jpg",
    joined: "09/18/14",
    email: "test@douglascollege.ca",
  },
  {
    name: "everett gordon",
    joined: "09/18/14",
    image: "https://randomuser.me/api/portraits/thumb/men/26.jpg",
    joined: "06/17/15",
    email: "test@douglascollege.ca",
  },
  {
    name: "aiden ma",
    image: "https://randomuser.me/api/portraits/thumb/men/82.jpg",
    joined: "07/18/12",
    email: "test@douglascollege.ca",
  },
  {
    name: "florent gerard",
    image: "https://randomuser.me/api/portraits/thumb/men/62.jpg",
    joined: "02/12/13",
    email: "test@douglascollege.ca",
  },
  {
    name: "amber chen",
    image: "https://randomuser.me/api/portraits/thumb/women/96.jpg",
    joined: "07/12/12",
    email: "test@douglascollege.ca",
  },
  {
    name: "alexandra davies",
    image: "https://randomuser.me/api/portraits/thumb/women/9.jpg",
    joined: "05/11/13",
    email: "test@douglascollege.ca",
  },
  {
    name: "sergio cole",
    image: "https://randomuser.me/api/portraits/thumb/men/57.jpg",
    joined: "02/17/15",
    email: "test@douglascollege.ca",
  },
  {
    name: "edgar dixon",
    image: "https://randomuser.me/api/portraits/thumb/men/98.jpg",
    joined: "06/17/11",
    email: "test@douglascollege.ca",
  },
  {
    name: "kirk myers",
    image: "https://randomuser.me/api/portraits/thumb/men/94.jpg",
    joined: "09/17/15",
    email: "test@douglascollege.ca",
  },
  {
    name: "ani hesseling",
    image: "https://randomuser.me/api/portraits/thumb/women/28.jpg",
    joined: "08/14/16",
    email: "test@douglascollege.ca",
  },
  {
    name: "victoire bonnet",
    image: "https://randomuser.me/api/portraits/thumb/women/24.jpg",
    joined: "05/13/16",
    email: "test@douglascollege.ca",
  },
  {
    name: "marcos morales",
    image: "https://randomuser.me/api/portraits/thumb/men/44.jpg",
    joined: "01/12/12",
    email: "test@douglascollege.ca",
  },
  {
    name: "nils neumann",
    image: "https://randomuser.me/api/portraits/thumb/men/75.jpg",
    joined: "03/11/12",
    email: "test@douglascollege.ca",
  },
  {
    name: "emily harrison",
    image: "https://randomuser.me/api/portraits/thumb/women/86.jpg",
    joined: "07/18/15",
    email: "test@douglascollege.ca",
  },
  {
    name: "matthew fortin",
    image: "https://randomuser.me/api/portraits/thumb/men/41.jpg",
    joined: "03/18/15",
    email: "test@douglascollege.ca",
  },
  {
    name: "charlotte steward",
    image: "https://randomuser.me/api/portraits/thumb/women/32.jpg",
    joined: "02/18/11",
    email: "test@douglascollege.ca",
  },
  {
    name: "marceau rodriguez",
    image: "https://randomuser.me/api/portraits/thumb/men/3.jpg",
    joined: "07/13/14",
    email: "test@douglascollege.ca",
  },
  {
    name: "hudson anderson",
    image: "https://randomuser.me/api/portraits/thumb/men/91.jpg",
    joined: "09/12/15",
    email: "test@douglascollege.ca",
  },
];
